name: Create Release

env:
  GITHUB_TOKEN: ${{ secrets.token }}

on:
  push:
    branches:
      - master

jobs:
  version:
    name: Version and Prerelease
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: paulhatch/semantic-version@v5.0.2
        id: version
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          change_path: .
          version_format: "${major}.${minor}.${patch}"

      - name: Create new Release with semantic-version tag
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          name: Release ${{ steps.version.outputs.version }}
          tag: ${{ steps.version.outputs.version }}
          body: Building Docker Image ${{ steps.version.outputs.version }} ...

  docker:
    needs:
      - version
    uses: ./.github/workflows/task-docker.yml
    with:
      registry: reg.h2-invent.com
      dockerfile_path: './Dockerfile'
      directory: '.'
      version: ${{ needs.version.outputs.version }}
      tags: reg.h2-invent.com/secure-document-share/core:${{ needs.version.outputs.version }},reg.h2-invent.com/secure-document-share/core:latest
    secrets:
      docker_password: ${{ secrets.HARBOR_PUSH_PASSWORD }}
      docker_username: ${{ secrets.HARBOR_PUSH_USERNAME }}

  release:
    needs:
      - version
      - docker
    uses: ./.github/workflows/task-release.yml
    with:
      version: ${{ needs.version.outputs.version }}
